// flow-typed signature: b8c121f288d6aff46a6e696c43c80637
// flow-typed version: <<STUB>>/laravel-mix_v^0.6.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laravel-mix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'laravel-mix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laravel-mix/setup/webpack.config' {
  declare module.exports: any;
}

declare module 'laravel-mix/setup/webpack.mix' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Collection' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Concat' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Dispatcher' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/EntryBuilder' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/File' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/index' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Manifest' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Mix' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Paths' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Verify' {
  declare module.exports: any;
}

declare module 'laravel-mix/src/Versioning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laravel-mix/setup/webpack.config.js' {
  declare module.exports: $Exports<'laravel-mix/setup/webpack.config'>;
}
declare module 'laravel-mix/setup/webpack.mix.js' {
  declare module.exports: $Exports<'laravel-mix/setup/webpack.mix'>;
}
declare module 'laravel-mix/src/Collection.js' {
  declare module.exports: $Exports<'laravel-mix/src/Collection'>;
}
declare module 'laravel-mix/src/Concat.js' {
  declare module.exports: $Exports<'laravel-mix/src/Concat'>;
}
declare module 'laravel-mix/src/Dispatcher.js' {
  declare module.exports: $Exports<'laravel-mix/src/Dispatcher'>;
}
declare module 'laravel-mix/src/EntryBuilder.js' {
  declare module.exports: $Exports<'laravel-mix/src/EntryBuilder'>;
}
declare module 'laravel-mix/src/File.js' {
  declare module.exports: $Exports<'laravel-mix/src/File'>;
}
declare module 'laravel-mix/src/index.js' {
  declare module.exports: $Exports<'laravel-mix/src/index'>;
}
declare module 'laravel-mix/src/Manifest.js' {
  declare module.exports: $Exports<'laravel-mix/src/Manifest'>;
}
declare module 'laravel-mix/src/Mix.js' {
  declare module.exports: $Exports<'laravel-mix/src/Mix'>;
}
declare module 'laravel-mix/src/Paths.js' {
  declare module.exports: $Exports<'laravel-mix/src/Paths'>;
}
declare module 'laravel-mix/src/Verify.js' {
  declare module.exports: $Exports<'laravel-mix/src/Verify'>;
}
declare module 'laravel-mix/src/Versioning.js' {
  declare module.exports: $Exports<'laravel-mix/src/Versioning'>;
}
