version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3.9-node-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/laravel
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:0TDHPEGpzH2EUUhOgrw/IcHF5M5vuBl3Zc5p0gMidVU=
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
      - JWT_SECRET: TYNxsCKFGRjMloeH6woMrRHFivyKt260
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev libpng-dev
      - run: sudo docker-php-ext-install zip pdo_mysql gd
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: php artisan migrate
      - run: php ./vendor/bin/phpunit
