export const START_SIGNUP = 'START_SIGNUP';
export const SIGNUP_CHANGE = 'signup/SIGNUP_CHANGE';
export const SUCCESS_SIGNUP = 'signup/SUCCESS_SIGNUP';
export const VERIFICATION_SUCCEEDED = 'signup/VERIFICATION_SUCCEEDED';
export const VERIFICATION_FAILED = 'signup/VERIFICATION_FAILED';
